spring:
  application:
    name: admin-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
feign:
  hystrix:
    enabled: true
server:
  port: 8755

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/